sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements-dev.txt

script:
    - python setup.py install
    - coverage run test.py -v

after_success:
    - codecov
